inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'archive/**/*'
    - 'design/**/*'
    - 'tools/**/*'
    - 'bin/**/*'
