version: "2.1"
services:
  db:
    image: openbuildservice/mariadb
  hackweek:
    build:
      dockerfile: Dockerfile
      context: .
    command: foreman start -p 3000
    volumes:
      - .:/hackweek
    ports:
      - "3000:3000"
    environment:
      - CONTAINER=1
    depends_on:
      - db
